parameters:
  masters:
    veer_lsu0:
      id_width: 3
      slaves: [mem0, uart, i3c]
    veer_ifu0:
      id_width: 3
      slaves: [mem0]
    veer_lsu1:
      id_width: 3
      slaves: [mem1, uart, i3c]
    veer_ifu1:
      id_width: 3
      slaves: [mem1]
  slaves:
    uart:
      offset: 0x30000000
      size: 0x1000
    i3c:
      offset: 0x30001000
      size: 0x1000
    mem0:
      offset : 0x80000000
      size: 0x1f400
    mem1:
      offset : 0x90000000
      size: 0x1f400
vlnv: 'vendor:library:axi_intercon:1.0'
